namespace PjtControlEPP.Formularios
{
    partial class FrmConsultaAutorizacion
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn4 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn8 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn9 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn10 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn11 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn5 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn12 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn13 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn6 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn14 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.TableViewDefinition tableViewDefinition2 = new Telerik.WinControls.UI.TableViewDefinition();
            this.dtgEPP = new Telerik.WinControls.UI.RadGridView();
            this.consultas = new PjtControlEPP.Consultas();
            this.consultaautorizacionBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.consultaautorizacionTableAdapter = new PjtControlEPP.ConsultasTableAdapters.consultaautorizacionTableAdapter();
            ((System.ComponentModel.ISupportInitialize)(this.dtgEPP)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dtgEPP.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.consultas)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.consultaautorizacionBindingSource)).BeginInit();
            this.SuspendLayout();
            // 
            // dtgEPP
            // 
            this.dtgEPP.Location = new System.Drawing.Point(12, 12);
            // 
            // 
            // 
            gridViewDecimalColumn4.DataType = typeof(int);
            gridViewDecimalColumn4.FieldName = "idfactura";
            gridViewDecimalColumn4.HeaderText = "NO FACTURA";
            gridViewDecimalColumn4.IsAutoGenerated = true;
            gridViewDecimalColumn4.Name = "idfactura";
            gridViewDecimalColumn4.Width = 80;
            gridViewTextBoxColumn8.FieldName = "NombreEmpleado";
            gridViewTextBoxColumn8.HeaderText = "NOMBRE EMPLEADO";
            gridViewTextBoxColumn8.IsAutoGenerated = true;
            gridViewTextBoxColumn8.Name = "NombreEmpleado";
            gridViewTextBoxColumn8.Width = 200;
            gridViewTextBoxColumn9.FieldName = "Cedula";
            gridViewTextBoxColumn9.HeaderText = "CEDULA";
            gridViewTextBoxColumn9.IsAutoGenerated = true;
            gridViewTextBoxColumn9.Name = "Cedula";
            gridViewTextBoxColumn9.Width = 100;
            gridViewTextBoxColumn10.FieldName = "OracleID";
            gridViewTextBoxColumn10.HeaderText = "ORACLE ID";
            gridViewTextBoxColumn10.IsAutoGenerated = true;
            gridViewTextBoxColumn10.Name = "OracleID";
            gridViewTextBoxColumn10.Width = 80;
            gridViewTextBoxColumn11.FieldName = "AreaTrabajo";
            gridViewTextBoxColumn11.HeaderText = "AREA DE TRABAJO";
            gridViewTextBoxColumn11.IsAutoGenerated = true;
            gridViewTextBoxColumn11.Name = "AreaTrabajo";
            gridViewTextBoxColumn11.Width = 150;
            gridViewDecimalColumn5.DataType = typeof(int);
            gridViewDecimalColumn5.FieldName = "idproducto";
            gridViewDecimalColumn5.HeaderText = "ITEM";
            gridViewDecimalColumn5.IsAutoGenerated = true;
            gridViewDecimalColumn5.Name = "idproducto";
            gridViewDecimalColumn5.Width = 80;
            gridViewTextBoxColumn12.FieldName = "nombreepp";
            gridViewTextBoxColumn12.HeaderText = "DESCRIPCION";
            gridViewTextBoxColumn12.IsAutoGenerated = true;
            gridViewTextBoxColumn12.Name = "nombreepp";
            gridViewTextBoxColumn12.Width = 200;
            gridViewTextBoxColumn13.FieldName = "fechavence";
            gridViewTextBoxColumn13.HeaderText = "FECHA VENCE";
            gridViewTextBoxColumn13.IsAutoGenerated = true;
            gridViewTextBoxColumn13.Name = "fechavence";
            gridViewTextBoxColumn13.Width = 80;
            gridViewDecimalColumn6.DataType = typeof(int);
            gridViewDecimalColumn6.FieldName = "codigoautorizacion";
            gridViewDecimalColumn6.HeaderText = "CODIGO AUTORIZACION";
            gridViewDecimalColumn6.IsAutoGenerated = true;
            gridViewDecimalColumn6.Name = "codigoautorizacion";
            gridViewDecimalColumn6.Width = 100;
            gridViewTextBoxColumn14.FieldName = "observacion";
            gridViewTextBoxColumn14.HeaderText = "OBSERVACION";
            gridViewTextBoxColumn14.IsAutoGenerated = true;
            gridViewTextBoxColumn14.Name = "observacion";
            gridViewTextBoxColumn14.Width = 150;
            this.dtgEPP.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewDecimalColumn4,
            gridViewTextBoxColumn8,
            gridViewTextBoxColumn9,
            gridViewTextBoxColumn10,
            gridViewTextBoxColumn11,
            gridViewDecimalColumn5,
            gridViewTextBoxColumn12,
            gridViewTextBoxColumn13,
            gridViewDecimalColumn6,
            gridViewTextBoxColumn14});
            this.dtgEPP.MasterTemplate.DataSource = this.consultaautorizacionBindingSource;
            this.dtgEPP.MasterTemplate.EnableFiltering = true;
            this.dtgEPP.MasterTemplate.ViewDefinition = tableViewDefinition2;
            this.dtgEPP.Name = "dtgEPP";
            this.dtgEPP.ReadOnly = true;
            this.dtgEPP.Size = new System.Drawing.Size(984, 612);
            this.dtgEPP.TabIndex = 0;
            this.dtgEPP.DoubleClick += new System.EventHandler(this.dtgEPP_DoubleClick_1);
            // 
            // consultas
            // 
            this.consultas.DataSetName = "Consultas";
            this.consultas.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            // 
            // consultaautorizacionBindingSource
            // 
            this.consultaautorizacionBindingSource.DataMember = "consultaautorizacion";
            this.consultaautorizacionBindingSource.DataSource = this.consultas;
            // 
            // consultaautorizacionTableAdapter
            // 
            this.consultaautorizacionTableAdapter.ClearBeforeFill = true;
            // 
            // FrmConsultaAutorizacion
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.ClientSize = new System.Drawing.Size(1008, 636);
            this.Controls.Add(this.dtgEPP);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.SizableToolWindow;
            this.Name = "FrmConsultaAutorizacion";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.FrmConsultaAutorizacion_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dtgEPP.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dtgEPP)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.consultas)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.consultaautorizacionBindingSource)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Telerik.WinControls.UI.RadGridView dtgEPP;
        private Consultas consultas;
        private System.Windows.Forms.BindingSource consultaautorizacionBindingSource;
        private ConsultasTableAdapters.consultaautorizacionTableAdapter consultaautorizacionTableAdapter;



    }
}