namespace PjtControlEPP.Formularios
{
    partial class FrmConsultaEmpeadoPorUsuario
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn1 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn2 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn3 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn4 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn5 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn6 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.TableViewDefinition tableViewDefinition1 = new Telerik.WinControls.UI.TableViewDefinition();
            this.dtgEmpleados = new Telerik.WinControls.UI.RadGridView();
            this.consultaEmpleadosPorUsuariosBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.consultas = new PjtControlEPP.Consultas();
            this.consultaEmpleadosPorUsuariosTableAdapter = new PjtControlEPP.ConsultasTableAdapters.ConsultaEmpleadosPorUsuariosTableAdapter();
            ((System.ComponentModel.ISupportInitialize)(this.dtgEmpleados)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dtgEmpleados.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.consultaEmpleadosPorUsuariosBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.consultas)).BeginInit();
            this.SuspendLayout();
            // 
            // dtgEmpleados
            // 
            this.dtgEmpleados.Location = new System.Drawing.Point(13, 13);
            // 
            // 
            // 
            gridViewDecimalColumn1.DataType = typeof(int);
            gridViewDecimalColumn1.FieldName = "idempleado";
            gridViewDecimalColumn1.HeaderText = "No";
            gridViewDecimalColumn1.IsAutoGenerated = true;
            gridViewDecimalColumn1.Name = "idempleado";
            gridViewDecimalColumn1.Width = 80;
            gridViewTextBoxColumn1.FieldName = "nombre";
            gridViewTextBoxColumn1.HeaderText = "Nombre";
            gridViewTextBoxColumn1.IsAutoGenerated = true;
            gridViewTextBoxColumn1.Name = "nombre";
            gridViewTextBoxColumn1.Width = 150;
            gridViewTextBoxColumn2.FieldName = "apellido";
            gridViewTextBoxColumn2.HeaderText = "Apellido";
            gridViewTextBoxColumn2.IsAutoGenerated = true;
            gridViewTextBoxColumn2.Name = "apellido";
            gridViewTextBoxColumn2.Width = 150;
            gridViewTextBoxColumn3.FieldName = "telefono";
            gridViewTextBoxColumn3.HeaderText = "Telefono";
            gridViewTextBoxColumn3.IsAutoGenerated = true;
            gridViewTextBoxColumn3.Name = "telefono";
            gridViewTextBoxColumn3.Width = 80;
            gridViewTextBoxColumn4.FieldName = "cedula";
            gridViewTextBoxColumn4.HeaderText = "Cedula";
            gridViewTextBoxColumn4.IsAutoGenerated = true;
            gridViewTextBoxColumn4.Name = "cedula";
            gridViewTextBoxColumn4.Width = 80;
            gridViewTextBoxColumn5.FieldName = "oracleid";
            gridViewTextBoxColumn5.HeaderText = "OracleID";
            gridViewTextBoxColumn5.IsAutoGenerated = true;
            gridViewTextBoxColumn5.Name = "oracleid";
            gridViewTextBoxColumn5.Width = 80;
            gridViewTextBoxColumn6.FieldName = "nombrearea";
            gridViewTextBoxColumn6.HeaderText = "Area";
            gridViewTextBoxColumn6.IsAutoGenerated = true;
            gridViewTextBoxColumn6.Name = "nombrearea";
            gridViewTextBoxColumn6.Width = 150;
            this.dtgEmpleados.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewDecimalColumn1,
            gridViewTextBoxColumn1,
            gridViewTextBoxColumn2,
            gridViewTextBoxColumn3,
            gridViewTextBoxColumn4,
            gridViewTextBoxColumn5,
            gridViewTextBoxColumn6});
            this.dtgEmpleados.MasterTemplate.DataSource = this.consultaEmpleadosPorUsuariosBindingSource;
            this.dtgEmpleados.MasterTemplate.EnableFiltering = true;
            this.dtgEmpleados.MasterTemplate.ViewDefinition = tableViewDefinition1;
            this.dtgEmpleados.Name = "dtgEmpleados";
            this.dtgEmpleados.ReadOnly = true;
            this.dtgEmpleados.Size = new System.Drawing.Size(794, 502);
            this.dtgEmpleados.TabIndex = 0;
            this.dtgEmpleados.DoubleClick += new System.EventHandler(this.radGridView1_DoubleClick);
            // 
            // consultaEmpleadosPorUsuariosBindingSource
            // 
            this.consultaEmpleadosPorUsuariosBindingSource.DataMember = "ConsultaEmpleadosPorUsuarios";
            this.consultaEmpleadosPorUsuariosBindingSource.DataSource = this.consultas;
            // 
            // consultas
            // 
            this.consultas.DataSetName = "Consultas";
            this.consultas.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            // 
            // consultaEmpleadosPorUsuariosTableAdapter
            // 
            this.consultaEmpleadosPorUsuariosTableAdapter.ClearBeforeFill = true;
            // 
            // FrmConsultaEmpeadoPorUsuario
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(814, 527);
            this.Controls.Add(this.dtgEmpleados);
            this.Name = "FrmConsultaEmpeadoPorUsuario";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FrmConsultaEmpeadoPorUsuario";
            this.Load += new System.EventHandler(this.FrmConsultaEmpeadoPorUsuario_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dtgEmpleados.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dtgEmpleados)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.consultaEmpleadosPorUsuariosBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.consultas)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Telerik.WinControls.UI.RadGridView dtgEmpleados;
        private Consultas consultas;
        private System.Windows.Forms.BindingSource consultaEmpleadosPorUsuariosBindingSource;
        private ConsultasTableAdapters.ConsultaEmpleadosPorUsuariosTableAdapter consultaEmpleadosPorUsuariosTableAdapter;
    }
}